script: misc updates

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,10 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 
 # script/bootstrap: Resolve all dependencies that the
 #                   application requires to run.
 
-# Navigate to source code root.
-cd "$(dirname "$0")/.."
+# Exit immediately if a command exits with a non-zero status
+set -e
 
 # Check if NPM is installed
 if command -v npm >/dev/null 2>&1; then
diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -1,14 +1,17 @@
-#!/bin/sh
+#!/bin/bash
 
 # script/server: Launch the application and any extra required processes
 #                locally.
 
-# Navigate to source code root.
-cd "$(dirname "$0")/.."
+# Exit immediately if a command exits with a non-zero status
+set -e
+
+# Store a local variable of the scripts current directory
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 # Check if NPM is installed
 if command -v npm >/dev/null 2>&1; then
-  script/update
+  ${DIR}/update
 
   echo "==> Launching application..."
   ionic serve
diff --git a/script/update b/script/update
--- a/script/update
+++ b/script/update
@@ -1,13 +1,16 @@
-#!/bin/sh
+#!/bin/bash
 
 # script/update: Update application to run for its current checkout.
 
-# Navigate to source code root.
-cd "$(dirname "$0")/.."
+# Exit immediately if a command exits with a non-zero status
+set -e
+
+# Store a local variable of the scripts current directory
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 # Check if NPM is installed
 if command -v npm >/dev/null 2>&1; then
-  script/bootstrap
+  ${DIR}/bootstrap
 
   echo '==> Updating NPM dependencies...'
   npm install
